name: 中青助力

on:
  workflow_dispatch:
  watch:
    types: started
  schedule:
    - cron: '13 8,2 * * *'
jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/licky009/Youthshare.git ~/main
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: npm install
        run: |
          cd ~/main
          npm install
          npm install cron
          npm install request
          npm install got
          npm install md5-node
      - name: '运行 【youthshare】'
        run: |
          cd ~/main
          node youthshare.js
